### ISSUE TITLE
Naming strategy db->clj

### ISSUE THREAD

**Issue by nenadalm** [r0man/sqlingvo#102]
Hi. It's possible to convert clojure keywords to column names: https://github.com/r0man/sqlingvo#naming-strategy.

Is it possible to also convert column names to clojure keywords? Maybe `:sql-keyword` option should do the trick (https://github.com/r0man/sqlingvo/blob/85a4668c71a427540a7c384fafefc319aea440ba/src/sqlingvo/util.cljc#L136)?

I am using sqlingvo.node but it doesn't use the function (https://github.com/r0man/sqlingvo.node/blob/6d1c7d536d4a858e0e653ce9fb05d9f17d01f31d/src/sqlingvo/node/driver.cljs#L20).

**Comment by r0man** [comment]
@nenadalm I think you are looking for this one: 

https://github.com/r0man/sqlingvo.node/blob/6d1c7d536d4a858e0e653ce9fb05d9f17d01f31d/test/sqlingvo/node/sync_test.cljs#L20

Or what do you mean by Clojure keywords?

**Comment by nenadalm** [comment]
`:sql-identifier` option seems to do nothing.

If I have `:sql-name` set to:
```clojure
(defn clj->db [s]
  (clojure.string/replace (name s) "-" "_"))
```

And there is table "user" with columns "first_name" and "id",
what I want is to be able to write something like:
```clojure
(sql/update db
             :user
           {:first-name "user1"}
           (sql/where '(= :id 1))
           (sql/returning :first-name))
```

and get result like:
```clojure
{:first-name "user1"}
```

currently, result looks like:
```clojure
{:first_name "user1"}
```

**Comment by r0man** [comment]
@nenadalm I think the test I linked above is exactly doing this. `information_schema` and `table_name` are underscored names in postgresql. and the result has the column names with hyphens. Are you sure you construct the database and pass it around correctly? If you can produce a minimal test case I can look at it.

**Comment by nenadalm** [comment]
I'm sorry. I've had db options in vector instead of map for some reason (which is why it didn't work).
