### ISSUE TITLE
Cast as schema-qualified type

### ISSUE THREAD

**Issue by deepxg** [r0man/sqlingvo#104]
The schema gets cut off expressions like:

`'(cast "value" :custom_schema.custom_type)`

This _can_ be fixed by checking the value using the `:form` or `:val` from the cast expression in the compiler but I wondered if there was a higher level fix that would work better. When the expression is parsed it's interpreted as a function call and the last argument as a table/column name, so perhaps there's an abstraction missing, albeit for quite a small edge-case.

**Comment by r0man** [comment]
Hey deepxg. There is parse-colum which you could use.

**Comment by r0man** [comment]
@deepxg This should be fixed in `0.9.21`.
